# Indexes of responses columns
INDEX_YEAR_OF_BIRTH = 1
INDEX_HEIGHT = 2
INDEX_WEIGHT = 3
INDEX_RUNNING_YEARS = 4
INDEX_TIME_1KM = 5
INDEX_TIME_5KM = 6
INDEX_TIME_10KM = 7
INDEX_TIME_21KM = 8
INDEX_TIME_42KM = 9
INDEX_TRAINING_AMOUNT = 10
INDEX_KM_AMOUNT = 11
INDEX_SPEED_TRAINING_AMOUNT = 12
INDEX_MINUTE_PER_KM_SPEED_TRAINING = 13
INDEX_THRESHOLD_TRAINING_AMOUNT = 14
INDEX_MINUTE_PER_KM_THRESHOLD_TRAINING = 15
INDEX_INTERVAL_TRAINING_AMOUNT = 16
INDEX_MINUTE_PER_KM_INTERVAL_TRAINING = 17
INDEX_RUN_UP_TRAINING_AMOUNT = 18
INDEX_MINUTE_PER_KM_RUN_UP_TRAINING = 19
INDEX_RUNWAY_AMOUNT = 20
INDEX_KM_PER_RUNWAY = 21
INDEX_MINUTE_PER_KM_RUNWAY = 22
INDEX_OTHER_TRAININGS = 23
INDEX_OTHER_TRAININGS_TYPES = 24
INDEX_OTHER_TRAININGS_AMOUNT = 25
INDEX_OTHER_TRAININGS_TIME = 26
INDEX_WELLNESS = 27
INDEX_WELLNESS_TYPES = 28
INDEX_WELLNESS_AMOUNT = 29
INDEX_DETRAINING_AMOUNT = 30
INDEX_DETRAINING_DAYS = 31
INDEX_WARMUP = 32
INDEX_WARMUP_TIME = 33

# Boolean str responses
STR_TRUE = 'tak'
STR_FALSE = 'nie'

# Separators
LIST_SEPARATOR = ';'


