# Generated by Django 3.1.5 on 2022-01-17 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('runtrainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fivekmtiming',
            old_name='name',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='halfmarathontiming',
            old_name='name',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='marathontiming',
            old_name='name',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='onekmtiming',
            old_name='name',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='runningtrainingtype',
            old_name='name',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='tenkmtiming',
            old_name='name',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='trainingprovider',
            old_name='name',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='trainingtiming',
            old_name='name',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='trainingtype',
            old_name='name',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='warmupfrequency',
            old_name='name',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='wellnesstype',
            old_name='name',
            new_name='description',
        ),
    ]
