# Generated by Django 3.1.5 on 2022-01-18 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runtrainapp', '0002_auto_20220117_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='runningtrainingtype',
            name='detailed_description',
            field=models.CharField(default=None, max_length=500),
            preserve_default=False,
        ),
    ]
