# Generated by Django 3.1.5 on 2022-01-21 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('runtrainapp', '0003_runningtrainingtype_detailed_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('time', models.IntegerField()),
                ('external_code', models.CharField(max_length=100)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='runtrainapp.trainingprovider')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='runtrainapp.trainingtype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RunningTraining',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('avg_speed', models.DecimalField(decimal_places=2, max_digits=10)),
                ('segments_amount', models.IntegerField()),
                ('avg_speed_per_segment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='runtrainapp.training')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='runtrainapp.runningtrainingtype')),
            ],
        ),
    ]
