# Generated by Django 3.1.5 on 2022-01-23 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('runtrainapp', '0004_runningtraining_training'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='runningtraining',
            name='avg_speed_per_segment',
        ),
    ]
