# Generated by Django 3.1.5 on 2022-01-23 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('runtrainapp', '0005_remove_runningtraining_avg_speed_per_segment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runningtraining',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='runtrainapp.runningtrainingtype'),
        ),
    ]
