# Generated by Django 3.1.5 on 2022-01-23 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('runtrainapp', '0006_auto_20220123_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runningtraining',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='runtrainapp.training', unique=True),
        ),
    ]
