# Generated by Django 3.1.5 on 2022-01-27 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('runtrainapp', '0008_auto_20220123_1321'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_of_birth', models.IntegerField()),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('running_years', models.IntegerField()),
                ('training_amount', models.IntegerField()),
                ('km_amount', models.IntegerField()),
                ('speed_training_amount', models.IntegerField()),
                ('threshold_training_amount', models.IntegerField()),
                ('interval_training_amount', models.IntegerField()),
                ('run_up_training_amount', models.IntegerField()),
                ('runway_amount', models.IntegerField()),
                ('km_per_runway', models.IntegerField()),
                ('other_trainings', models.BooleanField()),
                ('other_trainings_amount', models.IntegerField()),
                ('other_trainings_time', models.IntegerField()),
                ('wellness', models.BooleanField()),
                ('wellness_amount', models.IntegerField()),
                ('detraining_amount', models.IntegerField()),
                ('detraining_days', models.IntegerField()),
                ('warmup_time', models.IntegerField()),
                ('minute_per_km_interval_training', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='minute_per_km_interval_training', to='runtrainapp.trainingtiming')),
                ('minute_per_km_run_up_training', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='minute_per_km_run_up_training', to='runtrainapp.trainingtiming')),
                ('minute_per_km_runway', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='minute_per_km_runway', to='runtrainapp.trainingtiming')),
                ('minute_per_km_speed_training', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='minute_per_km_speed_training', to='runtrainapp.trainingtiming')),
                ('minute_per_km_threshold_training', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='minute_per_km_threshold_training', to='runtrainapp.trainingtiming')),
                ('time_10km', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='runtrainapp.tenkmtiming')),
                ('time_1km', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='runtrainapp.onekmtiming')),
                ('time_21km', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='runtrainapp.halfmarathontiming')),
                ('time_42km', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='runtrainapp.marathontiming')),
                ('time_5km', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='runtrainapp.fivekmtiming')),
                ('warmup', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='runtrainapp.warmupfrequency')),
            ],
        ),
        migrations.CreateModel(
            name='ResponseWellness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='runtrainapp.formresponse')),
                ('wellness_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='runtrainapp.wellnesstype')),
            ],
        ),
        migrations.CreateModel(
            name='ResponseOtherTraining',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other_training_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='runtrainapp.trainingtype')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='runtrainapp.formresponse')),
            ],
        ),
    ]
