# Generated by Django 3.1.5 on 2022-02-13 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runtrainapp', '0009_formresponse_responseothertraining_responsewellness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='external_code',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
